#!/bin/sh
code_base=`dirname "$0"`
tmp_dir=`mktemp -d /tmp/mkvtoolnix-ln-path-executables-XXXXXX`

if [ -d $tmp_dir ]; then
   rmdir $tmp_dir
fi

ln -s "$code_base" $tmp_dir

major=$(sysctl -b kern.osrelease); [ ${major/.*/} -le 10 ] && export DYLD_LIBRARY_PATH=${tmp_dir}/../Resources/snow_leopard/:$DYLD_LIBRARY_PATH
export PATH=$tmp_dir":"$PATH
export LANG=en_US.UTF-8

mmg "$@"

#exec done remove link
if [ -h $tmp_dir ]; then
   unlink $tmp_dir
fi

